export const en = {
  "app.name": "Partners",
  "app.partners": "Partners",
  "welcome.headline": "Jobs that come to your company.",
  "welcome.body": "Receive roadside and towing offers from MASAR, confirm them, and keep each job moving until it is done.",
  "auth.signIn": "Sign in",
  "auth.signUp": "Create account",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.passwordHint": "At least 8 characters.",
  "auth.newPassword": "New password (8+ characters)",
  "auth.forgot": "Forgot password?",
  "auth.noAccount": "No account yet? Create one",
  "auth.haveAccount": "Already have an account? Sign in",
  "auth.sameAccount": "Use the account your company invited. Access depends on your company membership.",
  "auth.signUpBody": "Create your account, then verify your email. Your company access is granted separately.",
  "auth.verifyTitle": "Verify your email",
  "auth.codeSent": "We sent a code to {email}.",
  "auth.code": "Verification code",
  "auth.verify": "Verify",
  "auth.resend": "Send the code again",
  "auth.changeEmail": "Use a different email",
  "auth.resetTitle": "Reset password",
  "auth.resetBody": "Enter your email and we will send a code.",
  "auth.sendCode": "Send code",
  "auth.resetDo": "Set new password",
  "auth.errCredentials": "Email or password is incorrect.",
  "auth.errCode": "That code is not correct.",
  "auth.errExpired": "The code expired. Request a new one.",
  "auth.errExists": "An account with this email already exists.",
  "auth.errPassword": "Choose a stronger password.",
  "auth.errRate": "Too many attempts. Wait a moment and try again.",
  "auth.errGeneric": "Sign-in could not be completed. Try again.",
  "auth.errSessionTask": "Complete the required security steps in the original MASAR app, then try signing in again.",
  "auth.authenticatorTitle": "Security verification",
  "auth.authenticatorBody": "Enter the current code from your authenticator app.",
  "cfg.partnerBackendTitle": "Partner service is not active yet",
  "cfg.partnerBackendBody": "Your MASAR account is connected. Company and job features still need to be activated on the central MASAR server.",
  "auth.notActive": "Sign-in is not active in this build: authentication is not configured.",
  "auth.unavailableTitle": "Sign-in is not configured",
  "auth.unavailableBody": "This build has no authentication key, so nobody can sign in yet. There is no demo mode.",
  "auth.unavailableHint": "Set EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY and rebuild.",
  "cfg.apiTitle": "Server address is not set",
  "cfg.apiMissing": "No API address is configured. Set EXPO_PUBLIC_API_URL or EXPO_PUBLIC_DOMAIN.",
  "cfg.apiInvalid": "EXPO_PUBLIC_API_URL must be a valid https address.",
  "common.back": "Back",
  "common.cancel": "Cancel",
  "common.edit": "Edit",
  "common.refresh": "Refresh",
  "common.retry": "Try again",
  "common.save": "Save",
  "err.title": "Something went wrong",
  "err.network": "Cannot reach the server. Check your connection.",
  "err.auth": "Your session expired. Sign in again.",
  "err.forbidden": "You do not have permission for this.",
  "err.notfound": "Not found.",
  "err.conflict": "This was changed by someone else. Latest data was reloaded; review and try again.",
  "err.invalid": "Some details are not valid. Check them and try again.",
  "err.server": "The server had a problem. Try again shortly.",
  "stale.error": "Could not refresh. Showing data from {time}.",
  "stale.old": "This data may be out of date (last updated {time}).",
  "tab.home": "Home",
  "tab.jobs": "Jobs",
  "tab.company": "Company",
  "tab.settings": "Settings",
  "gate.noCompany": "No company yet",
  "gate.noCompanyBody": "Register your company for review. You can edit your profile while you wait; jobs start after approval.",
  "gate.register": "Register a company",
  "dash.receiving": "Receiving offers",
  "dash.paused": "Paused",
  "dash.available": "Available for jobs",
  "dash.availableBody": "Turn off when you cannot take new jobs.",
  "dash.availableLocked": "Only the owner or a planner can change this.",
  "dash.inactive": "Your company is deactivated by MASAR.",
  "dash.reviewReason": "Reason from MASAR",
  "dash.noJobsUntilApproved": "Jobs are only sent to approved companies. You can still edit your profile.",
  "dash.completeProfile": "Edit company profile",
  "dash.offers": "Open offers",
  "dash.active": "Active jobs",
  "dash.nextOffer": "Next offer",
  "dash.emptyTitle": "Nothing waiting",
  "dash.emptyBody": "New offers appear here as soon as MASAR sends them.",
  "dash.emptyPaused": "You are paused, so no offers are sent. Turn availability on to receive them.",
  "cs.pending": "Pending review",
  "cs.approved": "Approved",
  "cs.rejected": "Rejected",
  "cs.blocked": "Blocked",
  "cs.pending.title": "Under review",
  "cs.pending.body": "MASAR is reviewing your company. You will not receive jobs until it is approved.",
  "cs.rejected.title": "Registration rejected",
  "cs.rejected.body": "Update your profile according to the reason below. You will not receive jobs.",
  "cs.blocked.title": "Company blocked",
  "cs.blocked.body": "This company cannot receive jobs. Contact MASAR.",
  "role.owner": "Owner",
  "role.planner": "Planner",
  "role.worker": "Worker",
  "ctype.towing": "Towing",
  "ctype.garage": "Garage",
  "ctype.both": "Towing and garage",
  "jobs.offers": "Offers",
  "jobs.active": "Active",
  "jobs.history": "History",
  "jobs.locked": "Jobs are locked",
  "jobs.noOffers": "No open offers",
  "jobs.noOffersBody": "Offers directed to your company show up here with a countdown.",
  "jobs.noActive": "No active jobs",
  "jobs.noActiveBody": "Accepted jobs stay here until completed.",
  "jobs.noActiveWorker": "Jobs assigned to you appear here.",
  "jobs.noHistory": "No history yet",
  "jobs.noHistoryBody": "Completed, declined and expired jobs are listed here.",
  "jobs.workerNote": "You only see jobs assigned to you.",
  "st.offered": "Offered",
  "st.accepted": "Accepted",
  "st.enroute": "On the way",
  "st.arrived": "Arrived",
  "st.completed": "Completed",
  "st.unavailable": "Unavailable",
  "st.declined": "Declined",
  "st.expired": "Expired",
  "offer.timeLeft": "Time left {time}",
  "offer.expired": "Offer expired",
  "offer.accept": "Accept job",
  "offer.decline": "Decline",
  "offer.serverNote": "The job is accepted only once the server confirms it.",
  "job.title": "Job",
  "job.noAccess": "You do not have access to this job.",
  "job.progress": "Progress",
  "job.location": "Location",
  "job.destination": "Destination",
  "job.vehicle": "Vehicle",
  "job.plate": "Plate",
  "job.notes": "Notes",
  "job.offeredAt": "Offered",
  "job.expiresAt": "Expires",
  "job.acceptedAt": "Accepted",
  "job.customer": "Customer",
  "job.phone": "Phone",
  "job.call": "Call customer",
  "job.hiddenUntilAccepted": "Customer details are shown after you accept.",
  "job.offerExpired": "This offer has expired.",
  "job.managersRespond": "Only the owner or a planner can answer offers.",
  "job.assign": "Assign a worker",
  "job.assignedToYou": "Assigned to you",
  "job.assignedOther": "A worker is assigned",
  "job.note": "Note (optional)",
  "job.unavailable": "Cannot complete",
  "job.unavailableBody": "Mark this job as unavailable? MASAR will be told.",
  "grp.tow": "Towing job steps",
  "grp.onsite": "On-site service steps",
  "grp.other": "Service steps",
  "step.tow.accepted": "Accepted",
  "step.tow.enroute": "Heading to the vehicle",
  "step.tow.arrived": "Arrived at the vehicle",
  "step.tow.completed": "Delivered",
  "step.onsite.accepted": "Accepted",
  "step.onsite.enroute": "On the way to the customer",
  "step.onsite.arrived": "Arrived, working on site",
  "step.onsite.completed": "Service completed",
  "step.other.accepted": "Accepted",
  "step.other.enroute": "On the way",
  "step.other.arrived": "Service started",
  "step.other.completed": "Completed",
  "svc.flat": "Flat tire",
  "svc.battery": "Battery",
  "svc.fuel": "Fuel",
  "svc.tow": "Towing",
  "svc.lockout": "Locked out",
  "svc.ev": "EV charging",
  "svc.other": "Other service",
  "preset.towing": "Towing",
  "preset.roadside": "Roadside help",
  "preset.tires": "Tires",
  "preset.battery": "Batteries",
  "preset.repair": "Repairs",
  "preset.ev": "EV",
  "company.edit": "Edit company",
  "company.media": "Logo, photos and documents",
  "company.members": "Members",
  "company.registerAnother": "Register another company",
  "reg.title": "Register company",
  "reg.subtitle": "Sent to MASAR for review",
  "reg.notice": "No jobs are sent until MASAR approves your company.",
  "reg.submit": "Submit for review",
  "edit.notApprovedNote": "You can edit now. Jobs start only after approval.",
  "form.name": "Company name",
  "form.type": "Type",
  "form.phone": "Phone",
  "form.contact": "Contact person",
  "form.address": "Address",
  "form.city": "City",
  "form.area": "Service area",
  "form.areaHint": "Where you can respond.",
  "form.hours": "Working hours",
  "form.hoursHint": "For example: Sat-Thu 08:00-20:00",
  "form.services": "Services",
  "form.customService": "Other service",
  "form.addService": "Add service",
  "form.required": "Required",
  "form.servicesRequired": "Choose at least one service.",
  "form.restored": "We restored your unsent changes.",
  "form.discard": "Discard draft",
  "media.logo": "Logo",
  "media.photos": "Photos",
  "media.docs": "Private documents",
  "media.noLogo": "No logo yet.",
  "media.noPhotos": "No photos yet.",
  "media.noDocs": "No documents yet.",
  "media.pickLogo": "Choose logo",
  "media.addPhoto": "Add photo",
  "media.addDoc": "Add document",
  "media.docsPrivate": "Only your company and MASAR can open these.",
  "media.imgLimits": "JPEG, PNG or WebP, up to 5 MB.",
  "media.docLimits": "PDF, JPEG or PNG, up to 10 MB.",
  "media.docN": "Document {n}",
  "media.view": "Open",
  "media.viewFail": "Could not open the document. Try again.",
  "media.done": "Uploaded.",
  "media.uploadFail": "Upload failed. Check your connection and try again.",
  "media.tooBig": "The file is larger than {mb} MB.",
  "media.badTypeImg": "Use a JPEG, PNG or WebP image.",
  "media.badTypeDoc": "Use a PDF, JPEG or PNG file.",
  "media.permDenied": "Photo access is off. Allow it in Settings to upload images.",
  "push.openSettings": "Open device settings",
  "push.denied": "Notifications are blocked. Allow them in device settings.",
  "push.failed": "Could not turn on notifications. Try again.",
  "push.removeFailed": "Could not turn off notifications on the server. Try again.",
  "push.na.web": "Push notifications are not available on the web.",
  "push.na.expogo": "Push notifications do not work in Expo Go. Use a development or production build.",
  "push.na.simulator": "Push notifications need a physical device.",
  "push.na.noproject": "Push is not configured in this build (Expo project ID is missing).",
  "mem.add": "Add member",
  "mem.addBody": "Enter the account ID of someone who already signed in to MASAR Partners.",
  "mem.userId": "Account ID",
  "mem.noOwner": "Members can be planners or workers only.",
  "mem.notFound": "No such account. Ask them to sign in first, then check the ID.",
  "mem.empty": "No members",
  "mem.emptyBody": "Add planners and workers by account ID.",
  "mem.inactive": "Inactive",
  "mem.active": "Active",
  "mem.deactivate": "Deactivate",
  "mem.reactivate": "Reactivate",
  "mem.ownerOnly": "Only the owner can add or change members.",
  "set.language": "Language",
  "set.push": "Notifications",
  "set.pushToggle": "New offer alerts",
  "set.pushBody": "A notification opens the job directly.",
  "set.company": "Active company",
  "set.operator": "MASAR operator",
  "set.account": "Account",
  "set.userId": "Account ID",
  "set.role": "Role",
  "set.server": "Server",
  "set.auth": "Sign-in",
  "set.active": "Active",
  "set.notConfigured": "Not configured",
  "set.signOut": "Sign out",
  "set.signOutBody": "Notifications on this device will be turned off.",
  "set.unregFail": "Notifications may continue",
  "set.unregFailBody": "We could not remove this device from the server. You may still receive alerts until it is removed.",
  "op.open": "Operator tools",
  "op.title": "Operator",
  "op.reviews": "Reviews",
  "op.dispatch": "Dispatch",
  "op.audit": "Audit",
  "op.noReviews": "No companies to review",
  "op.docs": "Documents",
  "op.reason": "Reason",
  "op.reasonRequired": "A reason is required to reject or block.",
  "op.approve": "Approve",
  "op.reject": "Reject",
  "op.block": "Block",
  "op.noRequests": "No requests to dispatch",
  "op.eligible": "Eligible companies",
  "op.noEligible": "No eligible companies",
  "op.expiresIn": "Offer valid for",
  "op.minutes": "{n} min",
  "op.sendOffer": "Send offer",
  "op.noAudit": "No audit entries",
} as const;

export type StringKey = keyof typeof en;

export const ar: Record<StringKey, string> = {
  "app.name": "الشركاء",
  "app.partners": "شركاء مسار",
  "welcome.headline": "الطلبات تصل إلى شركتك مباشرة",
  "welcome.body": "استلم عروض المساعدة على الطريق والسحب من مسار، أكّدها، وتابع كل طلب حتى يكتمل.",
  "auth.signIn": "تسجيل الدخول",
  "auth.signUp": "إنشاء حساب",
  "auth.email": "البريد الإلكتروني",
  "auth.password": "كلمة المرور",
  "auth.passwordHint": "8 أحرف على الأقل.",
  "auth.newPassword": "كلمة مرور جديدة (8 أحرف فأكثر)",
  "auth.forgot": "نسيت كلمة المرور؟",
  "auth.noAccount": "ليس لديك حساب؟ أنشئ حساباً",
  "auth.haveAccount": "لديك حساب؟ سجّل الدخول",
  "auth.sameAccount": "استخدم الحساب المرتبط بشركتك. يعتمد الوصول على عضويتك في الشركة.",
  "auth.signUpBody": "أنشئ حسابك ثم أكّد بريدك الإلكتروني. يُمنح الوصول إلى الشركة بشكل منفصل.",
  "auth.verifyTitle": "تأكيد البريد الإلكتروني",
  "auth.codeSent": "أرسلنا رمزاً إلى {email}.",
  "auth.code": "رمز التحقق",
  "auth.verify": "تحقق",
  "auth.resend": "أعد إرسال الرمز",
  "auth.changeEmail": "استخدم بريداً آخر",
  "auth.resetTitle": "إعادة تعيين كلمة المرور",
  "auth.resetBody": "أدخل بريدك الإلكتروني وسنرسل لك رمزاً.",
  "auth.sendCode": "إرسال الرمز",
  "auth.resetDo": "تعيين كلمة المرور",
  "auth.errCredentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
  "auth.errCode": "الرمز غير صحيح.",
  "auth.errExpired": "انتهت صلاحية الرمز. اطلب رمزاً جديداً.",
  "auth.errExists": "يوجد حساب بهذا البريد بالفعل.",
  "auth.errPassword": "اختر كلمة مرور أقوى.",
  "auth.errRate": "محاولات كثيرة. انتظر قليلاً ثم أعد المحاولة.",
  "auth.errGeneric": "تعذّر إكمال العملية. حاول مرة أخرى.",
  "auth.notActive": "تسجيل الدخول غير مفعّل في هذا الإصدار: لم يتم إعداد المصادقة.",
  "auth.unavailableTitle": "تسجيل الدخول غير مُعدّ",
  "auth.unavailableBody": "لا يحتوي هذا الإصدار على مفتاح مصادقة، لذلك لا يمكن لأحد تسجيل الدخول بعد. لا يوجد وضع تجريبي.",
  "auth.unavailableHint": "عيّن EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY ثم أعد البناء.",
  "cfg.apiTitle": "عنوان الخادم غير محدد",
  "cfg.apiMissing": "لم يتم تحديد عنوان الخادم. عيّن EXPO_PUBLIC_API_URL أو EXPO_PUBLIC_DOMAIN.",
  "cfg.apiInvalid": "يجب أن يكون EXPO_PUBLIC_API_URL عنوان https صالحاً.",
  "common.back": "رجوع",
  "common.cancel": "إلغاء",
  "common.edit": "تعديل",
  "common.refresh": "تحديث",
  "common.retry": "أعد المحاولة",
  "common.save": "حفظ",
  "err.title": "حدث خطأ ما",
  "err.network": "تعذّر الوصول إلى الخادم. تحقق من اتصالك.",
  "err.auth": "انتهت الجلسة. سجّل الدخول مجدداً.",
  "err.forbidden": "ليست لديك صلاحية لهذا الإجراء.",
  "err.notfound": "غير موجود.",
  "auth.errSessionTask": "أكمل خطوات الأمان المطلوبة في تطبيق مسار الأصلي، ثم حاول تسجيل الدخول مرة أخرى.",
  "auth.authenticatorTitle": "التحقق الأمني",
  "auth.authenticatorBody": "أدخل الرمز الحالي من تطبيق المصادقة الخاص بك.",
  "cfg.partnerBackendTitle": "خدمة الشركاء لم تُفعّل بعد",
  "cfg.partnerBackendBody": "تم ربط حساب مسار الخاص بك. يجب تفعيل خدمات الشركات والطلبات على خادم مسار المركزي.",
  "err.conflict": "تم تغيير هذه البيانات من طرف آخر. أُعيد تحميل أحدث البيانات، راجعها وحاول مجدداً.",
  "err.invalid": "بعض البيانات غير صالحة. راجعها وحاول مجدداً.",
  "err.server": "حدثت مشكلة في الخادم. حاول بعد قليل.",
  "stale.error": "تعذّر التحديث. تُعرض بيانات الساعة {time}.",
  "stale.old": "قد تكون هذه البيانات قديمة (آخر تحديث {time}).",
  "tab.home": "الرئيسية",
  "tab.jobs": "الطلبات",
  "tab.company": "الشركة",
  "tab.settings": "الإعدادات",
  "gate.noCompany": "لا توجد شركة بعد",
  "gate.noCompanyBody": "سجّل شركتك للمراجعة. يمكنك تعديل ملفك أثناء الانتظار، وتبدأ الطلبات بعد الموافقة.",
  "gate.register": "تسجيل شركة",
  "dash.receiving": "تستقبل العروض",
  "dash.paused": "متوقف مؤقتاً",
  "dash.available": "متاح للطلبات",
  "dash.availableBody": "أوقفه عندما لا تستطيع استلام طلبات جديدة.",
  "dash.availableLocked": "يمكن للمالك أو المخطّط فقط تغيير ذلك.",
  "dash.inactive": "تم تعطيل شركتك من قبل مسار.",
  "dash.reviewReason": "السبب من مسار",
  "dash.noJobsUntilApproved": "لا تُرسل الطلبات إلا للشركات المعتمدة. يمكنك تعديل ملفك في أي وقت.",
  "dash.completeProfile": "تعديل ملف الشركة",
  "dash.offers": "عروض مفتوحة",
  "dash.active": "طلبات جارية",
  "dash.nextOffer": "العرض التالي",
  "dash.emptyTitle": "لا شيء بانتظارك",
  "dash.emptyBody": "تظهر العروض الجديدة هنا فور إرسالها من مسار.",
  "dash.emptyPaused": "أنت متوقف مؤقتاً فلا تصلك عروض. فعّل التوفر لاستلامها.",
  "cs.pending": "قيد المراجعة",
  "cs.approved": "معتمدة",
  "cs.rejected": "مرفوضة",
  "cs.blocked": "محظورة",
  "cs.pending.title": "قيد المراجعة",
  "cs.pending.body": "تراجع مسار شركتك. لن تصلك طلبات قبل الموافقة.",
  "cs.rejected.title": "تم رفض التسجيل",
  "cs.rejected.body": "حدّث ملفك وفق السبب أدناه. لن تصلك طلبات.",
  "cs.blocked.title": "تم حظر الشركة",
  "cs.blocked.body": "لا يمكن لهذه الشركة استلام الطلبات. تواصل مع مسار.",
  "role.owner": "مالك",
  "role.planner": "مخطّط",
  "role.worker": "عامل",
  "ctype.towing": "سحب",
  "ctype.garage": "ورشة",
  "ctype.both": "سحب وورشة",
  "jobs.offers": "العروض",
  "jobs.active": "الجارية",
  "jobs.history": "السجل",
  "jobs.locked": "الطلبات مقفلة",
  "jobs.noOffers": "لا توجد عروض مفتوحة",
  "jobs.noOffersBody": "تظهر هنا العروض الموجهة لشركتك مع عدّاد تنازلي.",
  "jobs.noActive": "لا توجد طلبات جارية",
  "jobs.noActiveBody": "تبقى الطلبات المقبولة هنا حتى تكتمل.",
  "jobs.noActiveWorker": "تظهر هنا الطلبات المسندة إليك.",
  "jobs.noHistory": "لا يوجد سجل بعد",
  "jobs.noHistoryBody": "تُعرض هنا الطلبات المكتملة والمرفوضة والمنتهية.",
  "jobs.workerNote": "ترى فقط الطلبات المسندة إليك.",
  "st.offered": "معروض",
  "st.accepted": "مقبول",
  "st.enroute": "في الطريق",
  "st.arrived": "وصل",
  "st.completed": "مكتمل",
  "st.unavailable": "غير متاح",
  "st.declined": "مرفوض",
  "st.expired": "منتهي",
  "offer.timeLeft": "الوقت المتبقي {time}",
  "offer.expired": "انتهى العرض",
  "offer.accept": "قبول الطلب",
  "offer.decline": "رفض",
  "offer.serverNote": "لا يُعتبر الطلب مقبولاً إلا بعد تأكيد الخادم.",
  "job.title": "الطلب",
  "job.noAccess": "لا تملك صلاحية الوصول إلى هذا الطلب.",
  "job.progress": "التقدّم",
  "job.location": "الموقع",
  "job.destination": "الوجهة",
  "job.vehicle": "المركبة",
  "job.plate": "اللوحة",
  "job.notes": "ملاحظات",
  "job.offeredAt": "وقت العرض",
  "job.expiresAt": "ينتهي",
  "job.acceptedAt": "وقت القبول",
  "job.customer": "العميل",
  "job.phone": "الهاتف",
  "job.call": "اتصل بالعميل",
  "job.hiddenUntilAccepted": "تظهر بيانات العميل بعد القبول.",
  "job.offerExpired": "انتهى هذا العرض.",
  "job.managersRespond": "يمكن للمالك أو المخطّط فقط الرد على العروض.",
  "job.assign": "إسناد إلى عامل",
  "job.assignedToYou": "مسند إليك",
  "job.assignedOther": "تم إسناد عامل",
  "job.note": "ملاحظة (اختياري)",
  "job.unavailable": "لا يمكن الإكمال",
  "job.unavailableBody": "تعليم الطلب على أنه غير متاح؟ سيتم إبلاغ مسار.",
  "grp.tow": "خطوات طلب السحب",
  "grp.onsite": "خطوات الخدمة في الموقع",
  "grp.other": "خطوات الخدمة",
  "step.tow.accepted": "تم القبول",
  "step.tow.enroute": "التوجّه إلى المركبة",
  "step.tow.arrived": "الوصول إلى المركبة",
  "step.tow.completed": "تم التسليم",
  "step.onsite.accepted": "تم القبول",
  "step.onsite.enroute": "في الطريق إلى العميل",
  "step.onsite.arrived": "وصلنا، العمل في الموقع",
  "step.onsite.completed": "اكتملت الخدمة",
  "step.other.accepted": "تم القبول",
  "step.other.enroute": "في الطريق",
  "step.other.arrived": "بدأ العمل",
  "step.other.completed": "اكتمل",
  "svc.flat": "إطار مثقوب",
  "svc.battery": "بطارية",
  "svc.fuel": "وقود",
  "svc.tow": "سحب",
  "svc.lockout": "مفاتيح محبوسة",
  "svc.ev": "شحن كهربائي",
  "svc.other": "خدمة أخرى",
  "preset.towing": "سحب",
  "preset.roadside": "مساعدة على الطريق",
  "preset.tires": "إطارات",
  "preset.battery": "بطاريات",
  "preset.repair": "إصلاحات",
  "preset.ev": "سيارات كهربائية",
  "company.edit": "تعديل الشركة",
  "company.media": "الشعار والصور والمستندات",
  "company.members": "الأعضاء",
  "company.registerAnother": "تسجيل شركة أخرى",
  "reg.title": "تسجيل شركة",
  "reg.subtitle": "يُرسل إلى مسار للمراجعة",
  "reg.notice": "لن تصلك طلبات حتى توافق مسار على شركتك.",
  "reg.submit": "إرسال للمراجعة",
  "edit.notApprovedNote": "يمكنك التعديل الآن. تبدأ الطلبات بعد الموافقة فقط.",
  "form.name": "اسم الشركة",
  "form.type": "النوع",
  "form.phone": "الهاتف",
  "form.contact": "الشخص المسؤول",
  "form.address": "العنوان",
  "form.city": "المدينة",
  "form.area": "منطقة الخدمة",
  "form.areaHint": "المنطقة التي تستطيع تغطيتها.",
  "form.hours": "ساعات العمل",
  "form.hoursHint": "مثال: السبت-الخميس 08:00-20:00",
  "form.services": "الخدمات",
  "form.customService": "خدمة أخرى",
  "form.addService": "إضافة خدمة",
  "form.required": "مطلوب",
  "form.servicesRequired": "اختر خدمة واحدة على الأقل.",
  "form.restored": "استعدنا تعديلاتك غير المرسلة.",
  "form.discard": "تجاهل المسودة",
  "media.logo": "الشعار",
  "media.photos": "الصور",
  "media.docs": "مستندات خاصة",
  "media.noLogo": "لا يوجد شعار بعد.",
  "media.noPhotos": "لا توجد صور بعد.",
  "media.noDocs": "لا توجد مستندات بعد.",
  "media.pickLogo": "اختر الشعار",
  "media.addPhoto": "إضافة صورة",
  "media.addDoc": "إضافة مستند",
  "media.docsPrivate": "لا يفتحها إلا شركتك ومسار.",
  "media.imgLimits": "JPEG أو PNG أو WebP، حتى 5 ميغابايت.",
  "media.docLimits": "PDF أو JPEG أو PNG، حتى 10 ميغابايت.",
  "media.docN": "المستند {n}",
  "media.view": "فتح",
  "media.viewFail": "تعذّر فتح المستند. حاول مجدداً.",
  "media.done": "تم الرفع.",
  "media.uploadFail": "فشل الرفع. تحقق من اتصالك وحاول مجدداً.",
  "media.tooBig": "حجم الملف أكبر من {mb} ميغابايت.",
  "media.badTypeImg": "استخدم صورة JPEG أو PNG أو WebP.",
  "media.badTypeDoc": "استخدم ملف PDF أو JPEG أو PNG.",
  "media.permDenied": "الوصول إلى الصور مغلق. اسمح به من الإعدادات لرفع الصور.",
  "push.openSettings": "فتح إعدادات الجهاز",
  "push.denied": "الإشعارات محظورة. اسمح بها من إعدادات الجهاز.",
  "push.failed": "تعذّر تفعيل الإشعارات. حاول مجدداً.",
  "push.removeFailed": "تعذّر إيقاف الإشعارات على الخادم. حاول مجدداً.",
  "push.na.web": "الإشعارات الفورية غير متاحة على الويب.",
  "push.na.expogo": "لا تعمل الإشعارات في Expo Go. استخدم نسخة تطوير أو إنتاج.",
  "push.na.simulator": "تحتاج الإشعارات إلى جهاز حقيقي.",
  "push.na.noproject": "الإشعارات غير مُعدّة في هذا الإصدار (معرّف مشروع Expo غير موجود).",
  "mem.add": "إضافة عضو",
  "mem.addBody": "أدخل معرّف حساب شخص سجّل الدخول سابقاً إلى مسار للشركاء.",
  "mem.userId": "معرّف الحساب",
  "mem.noOwner": "يمكن أن يكون الأعضاء مخطّطين أو عمالاً فقط.",
  "mem.notFound": "لا يوجد حساب بهذا المعرّف. اطلب منه تسجيل الدخول أولاً ثم تحقق من المعرّف.",
  "mem.empty": "لا يوجد أعضاء",
  "mem.emptyBody": "أضف المخطّطين والعمال بمعرّف الحساب.",
  "mem.inactive": "غير نشط",
  "mem.active": "نشط",
  "mem.deactivate": "تعطيل",
  "mem.reactivate": "إعادة تفعيل",
  "mem.ownerOnly": "المالك فقط يستطيع إضافة الأعضاء أو تعديلهم.",
  "set.language": "اللغة",
  "set.push": "الإشعارات",
  "set.pushToggle": "تنبيهات العروض الجديدة",
  "set.pushBody": "يفتح الإشعار الطلب مباشرة.",
  "set.company": "الشركة الحالية",
  "set.operator": "مشغّل مسار",
  "set.account": "الحساب",
  "set.userId": "معرّف الحساب",
  "set.role": "الدور",
  "set.server": "الخادم",
  "set.auth": "تسجيل الدخول",
  "set.active": "مفعّل",
  "set.notConfigured": "غير مُعدّ",
  "set.signOut": "تسجيل الخروج",
  "set.signOutBody": "سيتم إيقاف الإشعارات على هذا الجهاز.",
  "set.unregFail": "قد تستمر الإشعارات",
  "set.unregFailBody": "تعذّر إزالة هذا الجهاز من الخادم. قد تصلك تنبيهات إلى أن تتم إزالته.",
  "op.open": "أدوات المشغّل",
  "op.title": "المشغّل",
  "op.reviews": "المراجعات",
  "op.dispatch": "الإسناد",
  "op.audit": "السجل",
  "op.noReviews": "لا شركات للمراجعة",
  "op.docs": "المستندات",
  "op.reason": "السبب",
  "op.reasonRequired": "السبب مطلوب للرفض أو الحظر.",
  "op.approve": "موافقة",
  "op.reject": "رفض",
  "op.block": "حظر",
  "op.noRequests": "لا توجد طلبات للإسناد",
  "op.eligible": "الشركات المؤهلة",
  "op.noEligible": "لا توجد شركات مؤهلة",
  "op.expiresIn": "مدة صلاحية العرض",
  "op.minutes": "{n} دقائق",
  "op.sendOffer": "إرسال العرض",
  "op.noAudit": "لا توجد سجلات",
};
